---
- name: Install Erlang
  become: yes
  yum:
      name: "https://www.rabbitmq.com/releases/erlang/erlang-18.1-1.el7.centos.x86_64.rpm"
      state: present
  when: rabbitmq_install and (ansible_distribution == "CentOS")  # now only works with centOS given the Erlang distribution-specific package

- name: Install RabbitMQ Package Key
  become: yes
  rpm_key:
      key: https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  when: rabbitmq_install and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")

- name: Install RabbitMQ
  become: yes
  yum:
      name: "https://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbitmq_version }}/rabbitmq-server-{{ rabbitmq_build }}.el7.noarch.rpm"
      state: latest
  when: rabbitmq_install and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")

- name: Install Custom Configuration File
  become: yes
  template:
      src: templates/rabbitmq.config.j2
      dest: /etc/rabbitmq/rabbitmq.config
      mode: 0444
      backup: yes
      force: yes
  when: rabbitmq_install

- name: Install Desired Plug-Ins
  become: yes
  rabbitmq_plugin:
      names: rabbitmq_management
      new_only: yes
      state: enabled
  when: rabbitmq_install

- name: Fix enabled_plugins file permissions
  become: yes
  file:
    path: /etc/rabbitmq
    mode: 0555
    recurse: yes

- name: Install firewalld
  become: yes
  package:
    name: firewalld
    state: latest

- name: Start firewalld
  become: yes
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Configure Firewall Rules
  become: yes
# -A INPUT -p tcp -m tcp --dport 5672  -j ACCEPT
  firewalld:
      immediate: true
      port: 5671-5672/tcp
      permanent: true
      state: enabled
  # AWS runs without the firewall enabled.  Need to figure out how to detect that.
  when: rabbitmq_install and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") and (ansible_virtualization_type == "xen")

- name: Configure Firewall Rules (Erlang)
  become: yes
  firewalld:
    immediate: true
    port: 25672/tcp
    permanent: true
    state: enabled
  when: rabbitmq_install and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") and (ansible_virtualization_type == "xen")

- name: Configure Firewall Rules (console)
  become: yes
  firewalld:
      immediate: true
      port: 15672/tcp
      permanent: true
      state: enabled
  # AWS runs without the firewall enabled.  Need to figure out how to detect that.
  when: rabbitmq_install and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") and (ansible_virtualization_type == "xen")

- name: Start RabbitMQ
  become: yes
  systemd:
      name: rabbitmq-server
      enabled: yes
      daemon_reload: yes
      state: restarted
  when: rabbitmq_install

- name: Allow RabbitMQ To Fully Start
  become: no
  pause:
      minutes: 1
  when: rabbitmq_install

- name: Install RabbitMQ Admin CLI
  become: yes
  get_url:
      url: "http://localhost:15672/cli/rabbitmqadmin"
      dest: "/usr/local/bin/rabbitmqadmin"
      mode: 0555
  when: rabbitmq_install
