---
- name: Install Erlang
  become: yes
  yum:
      name: "erlang"
      state: present
  when: rabbitmq_install and (ansible_distribution == "RedHat")

- name: Install RabbitMQ Package Key
  become: yes
  rpm_key:
      key: https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  when: rabbitmq_install and (ansible_distribution == "RedHat")

- name: Install RabbitMQ
  become: yes
  yum:
      name: "https://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbitmq_version }}/rabbitmq-server-{{ rabbitmq_build }}.noarch.rpm"
      state: present
  when: rabbitmq_install and (ansible_distribution == "RedHat")

- name: Install Custom Configuration File
  become: yes
  template:
      src: templates/rabbitmq.config.j2
      dest: /etc/rabbitmq/rabbitmq.config
      mode: 0444
      backup: yes
      force: yes
  when: rabbitmq_install

- name: Install Desired Plug-Ins
  become: yes
  rabbitmq_plugin:
      names: rabbitmq_management
      new_only: yes
      state: enabled
  when: rabbitmq_install

- name: Configure Firewall Rules
  become: yes
# -A INPUT -p tcp -m tcp --dport 5672  -j ACCEPT
  firewalld:
      immediate: true
      port: 5671-5672/tcp
      permanent: true
      state: enabled
  when: rabbitmq_install and (ansible_distribution == "RedHat")

- name: Configure Firewall Rules (console)
  become: yes
  firewalld:
      immediate: true
      port: 15672/tcp
      permanent: true
      state: enabled
  when: rabbitmq_install and (ansible_distribution == "RedHat")

- name: Start RabbitMQ
  become: yes
  systemd:
      name: rabbitmq-server
      enabled: yes
      daemon_reload: yes
      state: restarted
  when: rabbitmq_install
