---
- name: Install Erlang
  become: yes
  yum:
      name: "erlang"
      state: present
  when: rabbitmq_install and (ansible_distribution == "RedHat")

- name: Install RabbitMQ Package Key
  become: yes
  rpm_key:
      key: https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  when: rabbitmq_install and (ansible_distribution == "RedHat")

- name: Install RabbitMQ
  become: yes
  yum:
      name: "https://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbitmq_version }}/rabbitmq-server-{{ rabbitmq_build }}.noarch.rpm"
      state: present
  when: rabbitmq_install and (ansible_distribution == "RedHat")
